export enum CellType {
  link = 'link',
  name = 'name',
  gender = 'gender',
  image = 'image',
  location = 'location',
  species = 'species',
  status = 'status',
  type = 'type',
  affiliations = 'affiliations',
  apprentices = 'apprentices',
  born = 'born',
  bornLocation = 'bornLocation',
  cybernetics = 'cybernetics',
  died = 'died',
  diedLocation = 'diedLocation',
  eyeColor = 'eyeColor',
  hairColor = 'hairColor',
  height = 'height',
  homeworld = 'homeworld',
  masters = 'masters',
  skinColor = 'skinColor',
  wiki = 'wiki',
}
